export const dynamic = 'force-dynamic' 
export const revalidate = 0

import prisma from "@/app/lib/prisma";
import { NewTodo } from "@/todos";

import { TodosGrid } from "@/todos/components/TodosGrid";
// import { Todo } from '@prisma/client';


export const metadata = {
  title: "Todos los TODOS",
  description: "Generated by create next app",
};


export default async function ServerTodosPage() {

  const todos = await prisma.todo.findMany({ orderBy: { description: 'asc' } });
  console.log('construido');
  
  return (
    <>
      <span className="text-5xl mb-10">Sever Actions</span>
      <div className="w-full px-5 mx-5 my-5">
        <NewTodo />
      </div>
      
      <TodosGrid todos={todos} />
    </>
  );
}