import prisma from "@/app/lib/prisma";
import { TodosGrid } from "@/todos/components/todosGrid";
import { Todo } from '@prisma/client';


export const metadata = {
  title: "Todos los TODOS",
  description: "Generated by create next app",
};


export default async function RestTodosPage() {

  const todos = await prisma.todo.findMany({ orderBy: { description: 'asc' } });

  return (
    <div>
      {/* FORMULARIO PARA AGREGAR TODOS */}
      {/* {
        JSON.stringify(todos)
      } */}
      <TodosGrid todos={todos} />
    </div>
  );
}